name: Manage version of Python package

on:
  workflow_call:

jobs:
  increase-version-dev:
    name: Increase version dev
    runs-on: gha-ss-airflow-preprod-org-runners
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

  build-and-publish-dev:
    runs-on: gha-ss-airflow-preprod-org-runners
    needs: [increase-version-dev]
    uses: pepsico-ecommerce/data-platform-reusable/.github/workflows/build-push.yml@main
    with:
      repository_url: 'https://pepecomm.pe.jfrog.io/artifactory/api/pypi/pypi-dev/'
    secrets:
      UV_INDEX_JFROG_USERNAME: ${{ secrets.UV_INDEX_JFROG_USERNAME }}
      UV_INDEX_JFROG_PASSWORD: ${{ secrets.UV_INDEX_JFROG_PASSWORD }}
